### PR TITLE
chore: minor translation updates and consistency fixes

### PR DESCRIPTION
**Pull request by davidramos-om**
Hi there,

My apologies for the delay.

Here I am suggesting some minor improvements to translation based on common UI conventions

### CODE REVIEW

**Comment by davidramos-om** [comment]
Tomorrow I'm going to add Spanish and update the readme as well.

**Comment by ayangweb** [comment]
Thank you, that's great!

**Comment by ayangweb** [comment]
@davidramos-om 
Hey👋, excuse me, I've uploaded the [readme](https://github.com/ayangweb/EcoPaste/tree/readme) branch for your convenience to provide translations, you need to support `README.md` and `CONTRIBUTING.md`!

Since the language can be changed in the tray, you need to provide translations in the following files as well, thanks🥰!
`src-tauri/src/locales`
`src-tauri/src/core/tray.rs`

**Comment by ayangweb** [comment]
@davidramos-om Hey 👋, excuse me, if you have time to contribute Spanish, please refer:

https://github.com/ayangweb/EcoPaste/pull/226
https://github.com/ayangweb/EcoPaste/pull/228

**Pull request merged**
